"""init

Revision ID: 197f8e9ce146
Revises: 
Create Date: 2026-09-18 14:55:39.052370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '197f8e9ce146'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversaciones_indira',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('canal', sa.Enum('WEB', 'APP', name='canal_conversacion'), nullable=False),
    sa.Column('estado', sa.Enum('ACTIVA', 'CERRADA', name='estado_conversacion'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fuentes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('dominio', sa.String(length=255), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('config_scraper', sa.JSON(), nullable=False),
    sa.Column('frecuencia_minutos', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dominio')
    )
    op.create_table('personas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.UUID(), nullable=True),
    sa.Column('tipo_documento', sa.Enum('DNI', 'RUC', 'CE', 'PASAPORTE', name='tipo_documento'), nullable=True),
    sa.Column('numero_documento', sa.String(length=20), nullable=True),
    sa.Column('nombres', sa.String(length=200), nullable=False),
    sa.Column('apellidos', sa.String(length=200), nullable=False),
    sa.Column('nombres_alternativos', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('es_pep', sa.Boolean(), nullable=False),
    sa.Column('cargo_pep', sa.String(length=200), nullable=True),
    sa.Column('nivel_riesgo_score', sa.Float(), nullable=False),
    sa.Column('origen', sa.Enum('KOTLIN_SYNC', 'SCRAPER_DETECTADO', name='origen_persona'), nullable=False),
    sa.Column('estado_verificacion', sa.Enum('PENDIENTE', 'VERIFICADO', 'DESCARTADO', name='estado_verificacion_persona'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personas_numero_documento'), 'personas', ['numero_documento'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('canal', sa.Enum('CHAT_INDIRA', 'WEB', 'APP', name='canal_ticket'), nullable=False),
    sa.Column('tipo', sa.Enum('CONSULTA', 'REPORTE', 'SOPORTE', 'RECLAMO', name='tipo_ticket'), nullable=False),
    sa.Column('asunto', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.Enum('ABIERTO', 'EN_PROCESO', 'RESUELTO', 'CERRADO', name='estado_ticket'), nullable=False),
    sa.Column('prioridad', sa.Enum('BAJA', 'MEDIA', 'ALTA', name='prioridad_ticket'), nullable=False),
    sa.Column('creado_por', sa.Enum('USUARIO', 'INDIRA', name='creado_por_ticket'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articulos_raw',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fuente_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('hash_contenido', sa.String(length=64), nullable=False),
    sa.Column('titulo', sa.Text(), nullable=False),
    sa.Column('contenido_texto', sa.Text(), nullable=False),
    sa.Column('fecha_publicacion', sa.Date(), nullable=True),
    sa.Column('fecha_scrapeo', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('procesado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['fuente_id'], ['fuentes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_articulos_raw_hash_contenido'), 'articulos_raw', ['hash_contenido'], unique=False)
    op.create_table('mensajes_indira',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversacion_id', sa.UUID(), nullable=False),
    sa.Column('rol', sa.Enum('USER', 'ASSISTANT', 'TOOL', name='rol_mensaje_indira'), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('tokens_usados', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversacion_id'], ['conversaciones_indira.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mensajes_ticket',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('autor', sa.Enum('USUARIO', 'INDIRA', 'AGENTE_HUMANO', name='autor_mensaje_ticket'), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reportes_generados',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('solicitado_por_usuario_id', sa.UUID(), nullable=True),
    sa.Column('conversacion_id', sa.UUID(), nullable=True),
    sa.Column('tipo_reporte', sa.String(length=150), nullable=False),
    sa.Column('formato', sa.Enum('PDF', 'XLSX', 'JSON', name='formato_reporte'), nullable=False),
    sa.Column('parametros', sa.JSON(), nullable=False),
    sa.Column('url_archivo', sa.String(length=1000), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversacion_id'], ['conversaciones_indira.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('casos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('persona_id', sa.UUID(), nullable=False),
    sa.Column('articulo_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('ACUSACION', 'DENUNCIA', 'INVESTIGACION', 'SENTENCIA', 'ABSOLUCION', name='tipo_caso'), nullable=False),
    sa.Column('categoria_delito', sa.String(length=150), nullable=False),
    sa.Column('resumen', sa.Text(), nullable=False),
    sa.Column('url_fuente', sa.String(length=1000), nullable=False),
    sa.Column('score_confianza', sa.Float(), nullable=False),
    sa.Column('estado_revision', sa.Enum('PENDIENTE', 'VERIFICADO', 'DESCARTADO', name='estado_revision_caso'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['articulo_id'], ['articulos_raw.id'], ),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('casos')
    op.drop_table('reportes_generados')
    op.drop_table('mensajes_ticket')
    op.drop_table('mensajes_indira')
    op.drop_index(op.f('ix_articulos_raw_hash_contenido'), table_name='articulos_raw')
    op.drop_table('articulos_raw')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_personas_numero_documento'), table_name='personas')
    op.drop_table('personas')
    op.drop_table('fuentes')
    op.drop_table('conversaciones_indira')
    # ### end Alembic commands ###
