"""feedback y memoria de indira

Revision ID: 7dd117c1ba76
Revises: 197f8e9ce146
Create Date: 2026-09-18 15:42:24.516744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dd117c1ba76'
down_revision: Union[str, Sequence[str], None] = '197f8e9ce146'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ejemplos_verificados',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mensaje_origen_id', sa.UUID(), nullable=True),
    sa.Column('pregunta_usuario', sa.Text(), nullable=False),
    sa.Column('respuesta_indira', sa.Text(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mensaje_origen_id'], ['mensajes_indira.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    feedback_enum = sa.Enum('POSITIVO', 'NEGATIVO', name='feedback_mensaje_indira')
    feedback_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('mensajes_indira', sa.Column('feedback', feedback_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mensajes_indira', 'feedback')
    sa.Enum(name='feedback_mensaje_indira').drop(op.get_bind(), checkfirst=True)
    op.drop_table('ejemplos_verificados')
    # ### end Alembic commands ###
